### ISSUE TITLE
Fix Error 500 on sending share/delivery from user without password

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/D4S2#58]
From @johnbradley in https://github.com/Duke-GCB/DukeDSClient/issues/82:

> I get a 500 back when trying to send either a share or a delivery if my user isn't setup with a password in D4S2. It gets passed the POST step without an issue. In my testing D4S2 automatically sets up a user with a blank password if it is their first time using the service.
> 
> For this testing I am running the code from the share_delivery branch #85.
> 
> @dleehr Could we change this to return something like a 401 Unauthorized when the user has no password?

**Comment by dleehr** [comment]
@johnbradley what do you mean "my user isn't setup with a password"

**Comment by johnbradley** [comment]
D4S2 automatically creates a user for you the first time it sees you. When it does it leaves the password blank. I am trying to target new users with this check. So the first time they try to `share` or `deliver` they get a warning telling them how to email us so we can set them up.

**Comment by dleehr** [comment]
OK, but there is a `DukeDSUser` obhect with an API key in the database that matches the person sending the share/delivery, right? Otherwise they wouldn't be able to authenticate at all.

It sounds like the issue is that there is no `User` object, which contains group memberships and passwords at the django level.

It sounds like these improvements are part of #56, which is evolving into "onboarding/login usability improvements"

**Comment by dleehr** [comment]
Put another way - it sounds like this error would appear for users that are half set-up, not for new users that have not already loaded their API keys. Those users would be stopped by a 401 when they tried to do the initial `share` or `delivery`

**Comment by johnbradley** [comment]
I am getting 401 status codes consistently now. I think the 500 was due to unusual database setup. 
I had a user who was setup and had permissions. Created a share. Removed the user. Visited the admin website (which created the user with a blank password). Tried to resend the share.
Some of this was due to manually editing the database.

**Comment by dleehr** [comment]
Pulling some data out of logs reveals an

EmailTemplateException: User object not found in Share of Project: 3e5a365a-f7ef-468c-a3c3-aeb614f45e3b - test1 State: New

From https://github.com/Duke-GCB/D4S2/blob/fcc1d4e5a65e9d6dacfa1ba2310a1a577531675e/d4s2_api/models.py#L223, meaning the `DukeDSUser` object has no related `User` object.

```
[Wed Sep 28 13:14:33.037859 2016] [wsgi:error] [pid 15:tid 139657731811072] Internal Server Error: /api/v1/shares/4/send/
[Wed Sep 28 13:14:33.037888 2016] [wsgi:error] [pid 15:tid 139657731811072] Traceback (most recent call last):
[Wed Sep 28 13:14:33.037893 2016] [wsgi:error] [pid 15:tid 139657731811072]   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Wed Sep 28 13:14:33.037896 2016] [wsgi:error] [pid 15:tid 139657731811072]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Sep 28 13:14:33.037900 2016] [wsgi:error] [pid 15:tid 139657731811072]   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Wed Sep 28 13:14:33.037903 2016] [wsgi:error] [pid 15:tid 139657731811072]     return view_func(*args, **kwargs)
[Wed Sep 28 13:14:33.037906 2016] [wsgi:error] [pid 15:tid 139657731811072]   File "/usr/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
[Wed Sep 28 13:14:33.037909 2016] [wsgi:error] [pid 15:tid 139657731811072]     return self.dispatch(request, *args, **kwargs)
[Wed Sep 28 13:14:33.037912 2016] [wsgi:error] [pid 15:tid 139657731811072]   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
[Wed Sep 28 13:14:33.037915 2016] [wsgi:error] [pid 15:tid 139657731811072]     response = handler(request, *args, **kwargs)
[Wed Sep 28 13:14:33.037918 2016] [wsgi:error] [pid 15:tid 139657731811072]   File "/usr/src/app/d4s2_api/views.py", line 131, in send
[Wed Sep 28 13:14:33.037921 2016] [wsgi:error] [pid 15:tid 139657731811072]     message = ShareMessage(share)
[Wed Sep 28 13:14:33.037924 2016] [wsgi:error] [pid 15:tid 139657731811072]   File "/usr/src/app/d4s2_api/utils.py", line 41, in __init__
[Wed Sep 28 13:14:33.037927 2016] [wsgi:error] [pid 15:tid 139657731811072]     template_subject, template_body = delivery_details.get_share_template_text()
[Wed Sep 28 13:14:33.037930 2016] [wsgi:error] [pid 15:tid 139657731811072]   File "/usr/src/app/switchboard/dds_util.py", line 100, in get_share_template_text
[Wed Sep 28 13:14:33.037933 2016] [wsgi:error] [pid 15:tid 139657731811072]     email_template = EmailTemplate.for_share(self.delivery)
[Wed Sep 28 13:14:33.037936 2016] [wsgi:error] [pid 15:tid 139657731811072]   File "/usr/src/app/d4s2_api/models.py", line 235, in for_share
[Wed Sep 28 13:14:33.037939 2016] [wsgi:error] [pid 15:tid 139657731811072]     return cls.for_operation(share, type_name)
[Wed Sep 28 13:14:33.037942 2016] [wsgi:error] [pid 15:tid 139657731811072]   File "/usr/src/app/d4s2_api/models.py", line 223, in for_operation
[Wed Sep 28 13:14:33.037945 2016] [wsgi:error] [pid 15:tid 139657731811072]     raise EmailTemplateException('User object not found in {}'.format(operation))
[Wed Sep 28 13:14:33.037956 2016] [wsgi:error] [pid 15:tid 139657731811072] EmailTemplateException: User object not found in Share of Project: 3e5a365a-f7ef-468c-a3c3-aeb614f45e3b - test1 State: New
[Wed Sep 28 13:15:10.213859 2016] [wsgi:error] [pid 14:tid 139657723418368] Internal Server Error: /api/v1/shares/5/send/
[Wed Sep 28 13:15:10.213886 2016] [wsgi:error] [pid 14:tid 139657723418368] Traceback (most recent call last):
[Wed Sep 28 13:15:10.213890 2016] [wsgi:error] [pid 14:tid 139657723418368]   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Wed Sep 28 13:15:10.213894 2016] [wsgi:error] [pid 14:tid 139657723418368]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Sep 28 13:15:10.213897 2016] [wsgi:error] [pid 14:tid 139657723418368]   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Wed Sep 28 13:15:10.213900 2016] [wsgi:error] [pid 14:tid 139657723418368]     return view_func(*args, **kwargs)
[Wed Sep 28 13:15:10.213903 2016] [wsgi:error] [pid 14:tid 139657723418368]   File "/usr/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
[Wed Sep 28 13:15:10.213907 2016] [wsgi:error] [pid 14:tid 139657723418368]     return self.dispatch(request, *args, **kwargs)
[Wed Sep 28 13:15:10.213910 2016] [wsgi:error] [pid 14:tid 139657723418368]   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
[Wed Sep 28 13:15:10.213913 2016] [wsgi:error] [pid 14:tid 139657723418368]     response = handler(request, *args, **kwargs)
[Wed Sep 28 13:15:10.213916 2016] [wsgi:error] [pid 14:tid 139657723418368]   File "/usr/src/app/d4s2_api/views.py", line 131, in send
[Wed Sep 28 13:15:10.213919 2016] [wsgi:error] [pid 14:tid 139657723418368]     message = ShareMessage(share)
[Wed Sep 28 13:15:10.213922 2016] [wsgi:error] [pid 14:tid 139657723418368]   File "/usr/src/app/d4s2_api/utils.py", line 41, in __init__
[Wed Sep 28 13:15:10.213925 2016] [wsgi:error] [pid 14:tid 139657723418368]     template_subject, template_body = delivery_details.get_share_template_text()
[Wed Sep 28 13:15:10.213928 2016] [wsgi:error] [pid 14:tid 139657723418368]   File "/usr/src/app/switchboard/dds_util.py", line 100, in get_share_template_text
[Wed Sep 28 13:15:10.213931 2016] [wsgi:error] [pid 14:tid 139657723418368]     email_template = EmailTemplate.for_share(self.delivery)
[Wed Sep 28 13:15:10.213934 2016] [wsgi:error] [pid 14:tid 139657723418368]   File "/usr/src/app/d4s2_api/models.py", line 235, in for_share
[Wed Sep 28 13:15:10.213937 2016] [wsgi:error] [pid 14:tid 139657723418368]     return cls.for_operation(share, type_name)
[Wed Sep 28 13:15:10.213940 2016] [wsgi:error] [pid 14:tid 139657723418368]   File "/usr/src/app/d4s2_api/models.py", line 223, in for_operation
[Wed Sep 28 13:15:10.213944 2016] [wsgi:error] [pid 14:tid 139657723418368]     raise EmailTemplateException('User object not found in {}'.format(operation))
[Wed Sep 28 13:15:10.213947 2016] [wsgi:error] [pid 14:tid 139657723418368] EmailTemplateException: User object not found in Share of Project: 8c76c4c4-4a25-482f-9a41-5ae75d0bd689 - test2 State: New
[Wed Sep 28 13:17:01.943462 2016] [wsgi:error] [pid 15:tid 139657765381888] Internal Server Error: /api/v1/deliveries/3/send/
[Wed Sep 28 13:17:01.943482 2016] [wsgi:error] [pid 15:tid 139657765381888] Traceback (most recent call last):
[Wed Sep 28 13:17:01.943486 2016] [wsgi:error] [pid 15:tid 139657765381888]   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Wed Sep 28 13:17:01.943490 2016] [wsgi:error] [pid 15:tid 139657765381888]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Sep 28 13:17:01.943493 2016] [wsgi:error] [pid 15:tid 139657765381888]   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Wed Sep 28 13:17:01.943497 2016] [wsgi:error] [pid 15:tid 139657765381888]     return view_func(*args, **kwargs)
[Wed Sep 28 13:17:01.943507 2016] [wsgi:error] [pid 15:tid 139657765381888]   File "/usr/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
[Wed Sep 28 13:17:01.943510 2016] [wsgi:error] [pid 15:tid 139657765381888]     return self.dispatch(request, *args, **kwargs)
[Wed Sep 28 13:17:01.943513 2016] [wsgi:error] [pid 15:tid 139657765381888]   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
[Wed Sep 28 13:17:01.943516 2016] [wsgi:error] [pid 15:tid 139657765381888]     response = handler(request, *args, **kwargs)
[Wed Sep 28 13:17:01.943519 2016] [wsgi:error] [pid 15:tid 139657765381888]   File "/usr/src/app/d4s2_api/views.py", line 105, in send
[Wed Sep 28 13:17:01.943522 2016] [wsgi:error] [pid 15:tid 139657765381888]     message = DeliveryMessage(delivery, accept_url)
[Wed Sep 28 13:17:01.943525 2016] [wsgi:error] [pid 15:tid 139657765381888]   File "/usr/src/app/d4s2_api/utils.py", line 72, in __init__
[Wed Sep 28 13:17:01.943527 2016] [wsgi:error] [pid 15:tid 139657765381888]     template_subject, template_body = delivery_details.get_action_template_text('delivery')
[Wed Sep 28 13:17:01.943530 2016] [wsgi:error] [pid 15:tid 139657765381888]   File "/usr/src/app/switchboard/dds_util.py", line 107, in get_action_template_text
[Wed Sep 28 13:17:01.943533 2016] [wsgi:error] [pid 15:tid 139657765381888]     email_template = EmailTemplate.for_operation(self.delivery, action_name)
[Wed Sep 28 13:17:01.943536 2016] [wsgi:error] [pid 15:tid 139657765381888]   File "/usr/src/app/d4s2_api/models.py", line 223, in for_operation
[Wed Sep 28 13:17:01.943539 2016] [wsgi:error] [pid 15:tid 139657765381888]     raise EmailTemplateException('User object not found in {}'.format(operation))
[Wed Sep 28 13:17:01.943542 2016] [wsgi:error] [pid 15:tid 139657765381888] EmailTemplateException: User object not found in Delivery Project: 145a83dc-5222-4077-8ecc-d1ecf7f5e98b - tar_it 2016-09-28 13:16 State: New Performed by: 
```

**Comment by johnbradley** [comment]
Closing this because this was due to unrealistic setup. For new users I get back a 401 as expected.
