### ISSUE TITLE
Sending delivery fails with bad email lookup 

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/D4S2#96]
```
[Tue Oct 24 19:58:06.023300 2017] [wsgi:error] [pid 26:tid 139777135298304] ERROR:django.request:Internal Server Error: /api/v1/deliveries/36/send/
[Tue Oct 24 19:58:06.023601 2017] [wsgi:error] [pid 26:tid 139777135298304] Traceback (most recent call last):
[Tue Oct 24 19:58:06.023725 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Tue Oct 24 19:58:06.023877 2017] [wsgi:error] [pid 26:tid 139777135298304]     response = self.process_exception_by_middleware(e, request)
[Tue Oct 24 19:58:06.024026 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Tue Oct 24 19:58:06.024157 2017] [wsgi:error] [pid 26:tid 139777135298304]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Oct 24 19:58:06.024263 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Tue Oct 24 19:58:06.024362 2017] [wsgi:error] [pid 26:tid 139777135298304]     return view_func(*args, **kwargs)
[Tue Oct 24 19:58:06.024511 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
[Tue Oct 24 19:58:06.024654 2017] [wsgi:error] [pid 26:tid 139777135298304]     return self.dispatch(request, *args, **kwargs)
[Tue Oct 24 19:58:06.024747 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
[Tue Oct 24 19:58:06.024883 2017] [wsgi:error] [pid 26:tid 139777135298304]     response = self.handle_exception(exc)
[Tue Oct 24 19:58:06.024976 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
[Tue Oct 24 19:58:06.025103 2017] [wsgi:error] [pid 26:tid 139777135298304]     response = handler(request, *args, **kwargs)
[Tue Oct 24 19:58:06.025200 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/src/app/d4s2_api/views.py", line 108, in send
[Tue Oct 24 19:58:06.025293 2017] [wsgi:error] [pid 26:tid 139777135298304]     message.send()
[Tue Oct 24 19:58:06.025405 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/src/app/d4s2_api/utils.py", line 87, in send
[Tue Oct 24 19:58:06.025518 2017] [wsgi:error] [pid 26:tid 139777135298304]     self._message.send()
[Tue Oct 24 19:58:06.025606 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/local/lib/python2.7/site-packages/django/core/mail/message.py", line 292, in send
[Tue Oct 24 19:58:06.025692 2017] [wsgi:error] [pid 26:tid 139777135298304]     return self.get_connection(fail_silently).send_messages([self])
[Tue Oct 24 19:58:06.025805 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
[Tue Oct 24 19:58:06.025926 2017] [wsgi:error] [pid 26:tid 139777135298304]     sent = self._send(message)
[Tue Oct 24 19:58:06.026036 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 123, in _send
[Tue Oct 24 19:58:06.026150 2017] [wsgi:error] [pid 26:tid 139777135298304]     self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\\r\\n'))
[Tue Oct 24 19:58:06.026239 2017] [wsgi:error] [pid 26:tid 139777135298304]   File "/usr/local/lib/python2.7/smtplib.py", line 747, in sendmail
[Tue Oct 24 19:58:06.026375 2017] [wsgi:error] [pid 26:tid 139777135298304]     raise SMTPRecipientsRefused(senderrs)
[Tue Oct 24 19:58:06.026473 2017] [wsgi:error] [pid 26:tid 139777135298304] SMTPRecipientsRefused: {u'None': (550, '5.1.1 <None>... User unknown')}
```

**Comment by dleehr** [comment]
In this case, the delivery was created, but the POST to `/deliveries/:id/send` failed. The email address in the DukeDSUser object was empty, suggesting it was not populated by DukeDS

**Comment by dleehr** [comment]
Original email from sender:

> I am trying to deliver a project with ddsclient.  I get the following error message:
>
> $ ddsclient deliver -p xxx --user yyy --skip-copy --msg-file text.txt --resend
> Delivering project.
 > 
> Request to https://d4s2.gcb.duke.edu/api/v1/deliveries/36/send/ failed with 500:
> <h1>Server Error (500)</h1>.
> 
> Do you know what it means?

**Comment by johnbradley** [comment]
There are a good number of users with null email in the response from `https://api.dataservice.duke.edu/apiexplorer#!/users/getApiV1Users`.

**Comment by dleehr** [comment]
No longer a D4S2 issue since reorganizing models. datadelivery-ui filters out null emails and https://github.com/Duke-GCB/DukeDSClient/issues/234 will have DukeDSClient use affiliate search to handle this
